config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :user_applications
  resources :artifact_filters
  resources :api_keys
  resources :users
  resources :permissions
  resources :applications
  resources :source_vcs
  resources :source_vcs_repositories
  resources :source_vcs_servers
  resources :sources
  resources :configurations
  resources :deployments
  resources :environments
  resources :environment_groups
  resources :artifacts

  get 'dashboard', to: 'dashboard#index'

  # external api
  namespace :api, defaults: { format: 'json' } do
    resources :deployments
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/api_key.rb
class ApiKey < ApplicationRecord
  belongs_to :user
end

app/models/application.rb
class Application < ApplicationRecord
  has_many :artifacts
  has_many :deployments
  has_many :properties
end

app/models/artifact.rb
class Artifact < ApplicationRecord
  belongs_to :artifact_type
  belongs_to :application

  has_many :artifact_versions
  has_many :deployments
end

app/models/artifact_filter.rb
class ArtifactFilter < ApplicationRecord
end

app/models/artifact_type.rb
class ArtifactType < ApplicationRecord
  belongs_to :artifact_category
  has_many :artifacts
end

app/models/artifact_version.rb
class ArtifactVersion < ApplicationRecord
  has_many :artifacts
end

app/models/configuration.rb
class Configuration < ApplicationRecord

  belongs_to :user, optional: true

  # global config is implemented with class methods
  def self.set(key, value)
    c = find_or_initialize_by(user_id: 0, key: key)
    c.value = value
    c.save!
  end

  def self.get(key)
    c = find_or_initialize_by(user_id: 0, key: key)
    c.value
  end

end

app/models/deployment.rb
class Deployment < ApplicationRecord
  belongs_to :environment
  belongs_to :application
  belongs_to :artifact, optional: true #TODO: check later
  belongs_to :artifact_version, optional: true #TODO: check later

  # this class has custom columns, that are being
  # added (and removed) in the property task
  #
  # - database columns are being generated (and removed)
  #   depending on the user's configuration
  # - since we don't want to restart rails every time we
  #   change the config, we don't generate methods at
  #   rails startup (which is my preferred way otherwise)
  # - instead we use the no_method_found callback

  def method_missing(method, *args)
    puts "You called: #{method}(#{args.join(', ')})"
    puts "(You also passed it a block)" if block_given?
  end

end

app/models/deployment_mongo.rb
class DeploymentMongo < ApplicationMongoRecord

  include Extractable

  @@collection = $mongo_client[:deployments]
  # or shall we use a class instance variable instead?

  def initialize(data)
    @data = data.to_h
    #@data = @data['deployment'] if @data['deployment']
    # why .to_h? => because:
    # Method to_bson is deprecated and will be removed in Rails 5.1
    # http://stackoverflow.com/questions/38710904/how-do-i-resolve-the-deprecation-warning-method-to-hash-is-deprecated-and-will
  end

  def self.find(id)
    id = BSON::ObjectId(id) unless id.is_a? BSON::ObjectId
    @@collection.find(_id: id).first #TODO: what if multiple? impossible (I think)
  end

  def data
    @data
  end

  def mongo_id
    @mongo_id
  end

  def errors
    [ "some error message" ]
  end

  def save
    result = @@collection.insert_one(@data)
    if result.n < 1
      return false
    else
      @mongo_id = result.inserted_id
    end

    puts "mongo_id: #{@mongo_id}"
    #DeploymentJob.perform_later(mongo_id: @mongo_id)
    DeploymentJob.new.perform(mongo_id: @mongo_id)
  end
end

app/models/environment.rb
class Environment < ApplicationRecord
  belongs_to :environment_group
end

app/models/permission.rb
class Permission < ApplicationRecord
end

app/models/property.rb
class Property < ApplicationRecord

  belongs_to :application

  # each property (row here) has a column
  # in the deployments table


end

app/models/source.rb
class Source < ApplicationRecord
end

app/models/source_vcs.rb
class SourceVcs < ApplicationRecord
end

app/models/source_vcs_repository.rb
class SourceVcsRepository < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

  has_many :api_keys
  has_many :configurations

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # :database_authenticatable, :registerable,
  # :recoverable, :rememberable, :trackable, :validatable
  devise :database_authenticatable, :lockable,
         :recoverable, :rememberable, :validatable
end

app/models/user_application.rb
class UserApplication < ApplicationRecord
end

app/controllers/source_vcs_repositories_controller.rb
class SourceVcsRepositoriesController < ApplicationController
  before_action :set_source_vcs_repository, only: [:show, :edit, :update, :destroy]

  # GET /source_vcs_repositories
  # GET /source_vcs_repositories.json
  def index
    @source_vcs_repositories = SourceVcsRepository.all
  end

  # GET /source_vcs_repositories/1
  # GET /source_vcs_repositories/1.json
  def show
  end

  # GET /source_vcs_repositories/new
  def new
    @source_vcs_repository = SourceVcsRepository.new
  end

  # GET /source_vcs_repositories/1/edit
  def edit
  end

  # POST /source_vcs_repositories
  # POST /source_vcs_repositories.json
  def create
    @source_vcs_repository = SourceVcsRepository.new(source_vcs_repository_params)

    respond_to do |format|
      if @source_vcs_repository.save
        format.html { redirect_to @source_vcs_repository, notice: 'Source vcs repository was successfully created.' }
        format.json { render :show, status: :created, location: @source_vcs_repository }
      else
        format.html { render :new }
        format.json { render json: @source_vcs_repository.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /source_vcs_repositories/1
  # PATCH/PUT /source_vcs_repositories/1.json
  def update
    respond_to do |format|
      if @source_vcs_repository.update(source_vcs_repository_params)
        format.html { redirect_to @source_vcs_repository, notice: 'Source vcs repository was successfully updated.' }
        format.json { render :show, status: :ok, location: @source_vcs_repository }
      else
        format.html { render :edit }
        format.json { render json: @source_vcs_repository.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /source_vcs_repositories/1
  # DELETE /source_vcs_repositories/1.json
  def destroy
    @source_vcs_repository.destroy
    respond_to do |format|
      format.html { redirect_to source_vcs_repositories_url, notice: 'Source vcs repository was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_source_vcs_repository
      @source_vcs_repository = SourceVcsRepository.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def source_vcs_repository_params
      params.require(:source_vcs_repository).permit(:server_id, :name, :shortname)
    end
end

app/helpers/api_keys_helper.rb
module ApiKeysHelper
end

app/helpers/artifacts_helper.rb
module ArtifactsHelper
end

app/helpers/source_vcs_repositories_helper.rb
module SourceVcsRepositoriesHelper
end

app/helpers/sources_helper.rb
module SourcesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/source_vcs_repositories/_form.html.erb
<%= form_for(source_vcs_repository) do |f| %>
  <% if source_vcs_repository.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(source_vcs_repository.errors.count, "error") %> prohibited this source_vcs_repository from being saved:</h2>

      <ul>
      <% source_vcs_repository.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :server_id %>
    <%= f.number_field :server_id %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :shortname %>
    <%= f.text_field :shortname %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/source_vcs_repositories/edit.html.erb
<h1>Editing Source Vcs Repository</h1>

<%= render 'form', source_vcs_repository: @source_vcs_repository %>

<%= link_to 'Show', @source_vcs_repository %> |
<%= link_to 'Back', source_vcs_repositories_path %>

app/views/source_vcs_repositories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Source Vcs Repositories</h1>

<table>
  <thead>
    <tr>
      <th>Server</th>
      <th>Name</th>
      <th>Shortname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @source_vcs_repositories.each do |source_vcs_repository| %>
      <tr>
        <td><%= source_vcs_repository.server_id %></td>
        <td><%= source_vcs_repository.name %></td>
        <td><%= source_vcs_repository.shortname %></td>
        <td><%= link_to 'Show', source_vcs_repository %></td>
        <td><%= link_to 'Edit', edit_source_vcs_repository_path(source_vcs_repository) %></td>
        <td><%= link_to 'Destroy', source_vcs_repository, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Source Vcs Repository', new_source_vcs_repository_path %>

app/views/source_vcs_repositories/new.html.erb
<h1>New Source Vcs Repository</h1>

<%= render 'form', source_vcs_repository: @source_vcs_repository %>

<%= link_to 'Back', source_vcs_repositories_path %>

app/views/source_vcs_repositories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Server:</strong>
  <%= @source_vcs_repository.server_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @source_vcs_repository.name %>
</p>

<p>
  <strong>Shortname:</strong>
  <%= @source_vcs_repository.shortname %>
</p>

<%= link_to 'Edit', edit_source_vcs_repository_path(@source_vcs_repository) %> |
<%= link_to 'Back', source_vcs_repositories_path %>