config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :user_applications
  resources :artifact_filters
  resources :api_keys
  resources :users
  resources :permissions
  resources :applications
  resources :source_vcs
  resources :source_vcs_repositories
  resources :source_vcs_servers
  resources :sources
  resources :configurations
  resources :deployments
  resources :environments
  resources :environment_groups
  resources :artifacts

  get 'dashboard', to: 'dashboard#index'

  # external api
  namespace :api, defaults: { format: 'json' } do
    resources :deployments
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/api_key.rb
class ApiKey < ApplicationRecord
  belongs_to :user
end

app/models/application.rb
class Application < ApplicationRecord
  has_many :artifacts
  has_many :deployments
  has_many :properties
end

app/models/artifact.rb
class Artifact < ApplicationRecord
  belongs_to :artifact_type
  belongs_to :application

  has_many :artifact_versions
  has_many :deployments
end

app/models/artifact_category.rb
class ArtifactCategory < ApplicationRecord
  has_many :artifact_types
end

app/models/artifact_filter.rb
class ArtifactFilter < ApplicationRecord
end

app/models/artifact_type.rb
class ArtifactType < ApplicationRecord
  belongs_to :artifact_category
  has_many :artifacts
end

app/models/artifact_version.rb
class ArtifactVersion < ApplicationRecord
  has_many :artifacts
end

app/models/configuration.rb
class Configuration < ApplicationRecord

  belongs_to :user, optional: true

  # global config is implemented with class methods
  def self.set(key, value)
    c = find_or_initialize_by(user_id: 0, key: key)
    c.value = value
    c.save!
  end

  def self.get(key)
    c = find_or_initialize_by(user_id: 0, key: key)
    c.value
  end

end

app/models/deployment.rb
class Deployment < ApplicationRecord
  belongs_to :environment
  belongs_to :application
  belongs_to :artifact, optional: true #TODO: check later
  belongs_to :artifact_version, optional: true #TODO: check later

  # this class has custom columns, that are being
  # added (and removed) in the property task
  #
  # - database columns are being generated (and removed)
  #   depending on the user's configuration
  # - since we don't want to restart rails every time we
  #   change the config, we don't generate methods at
  #   rails startup (which is my preferred way otherwise)
  # - instead we use the no_method_found callback

  def method_missing(method, *args)
    puts "You called: #{method}(#{args.join(', ')})"
    puts "(You also passed it a block)" if block_given?
  end

end

app/models/deployment_mongo.rb
class DeploymentMongo < ApplicationMongoRecord

  include Extractable

  @@collection = $mongo_client[:deployments]
  # or shall we use a class instance variable instead?

  def initialize(data)
    @data = data.to_h
    #@data = @data['deployment'] if @data['deployment']
    # why .to_h? => because:
    # Method to_bson is deprecated and will be removed in Rails 5.1
    # http://stackoverflow.com/questions/38710904/how-do-i-resolve-the-deprecation-warning-method-to-hash-is-deprecated-and-will
  end

  def self.find(id)
    id = BSON::ObjectId(id) unless id.is_a? BSON::ObjectId
    @@collection.find(_id: id).first #TODO: what if multiple? impossible (I think)
  end

  def data
    @data
  end

  def mongo_id
    @mongo_id
  end

  def errors
    [ "some error message" ]
  end

  def save
    result = @@collection.insert_one(@data)
    if result.n < 1
      return false
    else
      @mongo_id = result.inserted_id
    end

    puts "mongo_id: #{@mongo_id}"
    #DeploymentJob.perform_later(mongo_id: @mongo_id)
    DeploymentJob.new.perform(mongo_id: @mongo_id)
  end
end

app/models/environment.rb
class Environment < ApplicationRecord
  belongs_to :environment_group
end

app/models/permission.rb
class Permission < ApplicationRecord
end

app/models/property.rb
class Property < ApplicationRecord

  belongs_to :application

  # each property (row here) has a column
  # in the deployments table


end

app/models/source.rb
class Source < ApplicationRecord
end

app/models/source_vcs.rb
class SourceVcs < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

  has_many :api_keys
  has_many :configurations

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # :database_authenticatable, :registerable,
  # :recoverable, :rememberable, :trackable, :validatable
  devise :database_authenticatable, :lockable,
         :recoverable, :rememberable, :validatable
end

app/models/user_application.rb
class UserApplication < ApplicationRecord
end

app/controllers/api_keys_controller.rb
class ApiKeysController < ApplicationController
  before_action :set_api_key, only: [:show, :edit, :update, :destroy]

  # GET /api_keys
  # GET /api_keys.json
  def index
    @api_keys = ApiKey.all
  end

  # GET /api_keys/1
  # GET /api_keys/1.json
  def show
  end

  # GET /api_keys/new
  def new
    @api_key = ApiKey.new
  end

  # GET /api_keys/1/edit
  def edit
  end

  # POST /api_keys
  # POST /api_keys.json
  def create
    @api_key = ApiKey.new(api_key_params)

    respond_to do |format|
      if @api_key.save
        format.html { redirect_to @api_key, notice: 'Api key was successfully created.' }
        format.json { render :show, status: :created, location: @api_key }
      else
        format.html { render :new }
        format.json { render json: @api_key.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /api_keys/1
  # PATCH/PUT /api_keys/1.json
  def update
    respond_to do |format|
      if @api_key.update(api_key_params)
        format.html { redirect_to @api_key, notice: 'Api key was successfully updated.' }
        format.json { render :show, status: :ok, location: @api_key }
      else
        format.html { render :edit }
        format.json { render json: @api_key.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /api_keys/1
  # DELETE /api_keys/1.json
  def destroy
    @api_key.destroy
    respond_to do |format|
      format.html { redirect_to api_keys_url, notice: 'Api key was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_api_key
      @api_key = ApiKey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def api_key_params
      params.require(:api_key).permit(:user_id, :name, :active, :key)
    end
end

app/helpers/api_keys_helper.rb
module ApiKeysHelper
end

app/helpers/artifacts_helper.rb
module ArtifactsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/sources_helper.rb
module SourcesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/api_keys/_form.html.erb
<%= form_for(api_key) do |f| %>
  <% if api_key.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(api_key.errors.count, "error") %> prohibited this api_key from being saved:</h2>

      <ul>
      <% api_key.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :active %>
    <%= f.check_box :active %>
  </div>

  <div class="field">
    <%= f.label :key %>
    <%= f.text_field :key %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/api_keys/edit.html.erb
<h1>Editing Api Key</h1>

<%= render 'form', api_key: @api_key %>

<%= link_to 'Show', @api_key %> |
<%= link_to 'Back', api_keys_path %>

app/views/api_keys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Api Keys</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Name</th>
      <th>Active</th>
      <th>Key</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @api_keys.each do |api_key| %>
      <tr>
        <td><%= api_key.user_id %></td>
        <td><%= api_key.name %></td>
        <td><%= api_key.active %></td>
        <td><%= api_key.key %></td>
        <td><%= link_to 'Show', api_key %></td>
        <td><%= link_to 'Edit', edit_api_key_path(api_key) %></td>
        <td><%= link_to 'Destroy', api_key, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Api Key', new_api_key_path %>

app/views/api_keys/new.html.erb
<h1>New Api Key</h1>

<%= render 'form', api_key: @api_key %>

<%= link_to 'Back', api_keys_path %>

app/views/api_keys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @api_key.user_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @api_key.name %>
</p>

<p>
  <strong>Active:</strong>
  <%= @api_key.active %>
</p>

<p>
  <strong>Key:</strong>
  <%= @api_key.key %>
</p>

<%= link_to 'Edit', edit_api_key_path(@api_key) %> |
<%= link_to 'Back', api_keys_path %>